spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/consumo_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: minha-chave-jwt-super-segura-12345678901234567890
    expiration: 86400000